"""Demo seed data for Phase 1 (Master Data, Companies, Projects, Tasks, Time Tracking).

Kept in one place so later phases (Finance, CRM, ...) can add rows that
reference these same IDs without hunting through sheet-builder code.
"""
from datetime import date

TODAY = date(2026, 7, 28)

# ---- Lookup lists -------------------------------------------------------
LOOKUPS = {
    "Departments": ["Engineering", "Product", "Design", "Marketing", "Sales",
                     "Finance", "Operations", "Customer Success", "Legal", "HR"],
    "Priority Levels": ["Critical", "High", "Medium", "Low"],
    "Statuses": ["Not Started", "In Progress", "Blocked", "In Review",
                 "Completed", "Cancelled", "On Hold"],
    "Company Status": ["Active", "Paused", "Archived", "Exploring"],
    "Company Stage": ["Idea", "Pre-Launch", "Launched", "Growth", "Scaling", "Mature"],
    "Task Types": ["Feature", "Bug", "Research", "Admin", "Meeting", "Content", "Design", "Ops"],
    "Currencies": ["USD", "GBP", "EUR", "PKR", "AED", "INR", "CAD", "AUD"],
    "Time Categories": ["Deep Work", "Shallow Work", "Meeting", "Admin", "Learning"],
    "Billable": ["Yes", "No"],
    "Employee Status": ["Active", "Inactive", "On Leave"],
}

# ---- Employees ------------------------------------------------------------
# (Name, Email, Role, Department, Primary Company, Status, Start Date, Skills)
EMPLOYEES = [
    ("Humayra Shajahan", "humayrashajahan@gmail.com", "Founder / CEO", "Operations", "COMP-0001", "Active", date(2023, 1, 10), "Strategy, Fundraising, Product"),
    ("Ali Raza", "ali.raza@example.com", "Lead Engineer", "Engineering", "COMP-0001", "Active", date(2023, 3, 1), "Python, React, AWS"),
    ("Sara Khan", "sara.khan@example.com", "Product Designer", "Design", "COMP-0001", "Active", date(2023, 6, 15), "Figma, UX Research"),
    ("Bilal Ahmed", "bilal.ahmed@example.com", "Growth Marketer", "Marketing", "COMP-0002", "Active", date(2024, 1, 5), "SEO, Paid Ads, Content"),
    ("Nadia Farooq", "nadia.farooq@example.com", "Ops Manager", "Operations", "COMP-0002", "Active", date(2024, 2, 20), "Logistics, Vendor Mgmt"),
    ("Omar Siddiqui", "omar.siddiqui@example.com", "Full-Stack Engineer", "Engineering", "COMP-0003", "Active", date(2024, 8, 1), "Node.js, Postgres"),
]

# ---- Companies --------------------------------------------------------
# id will be auto-generated by formula; we just provide the seed fields in order
COMPANIES = [
    dict(name="Nimbus Analytics", legal="Nimbus Analytics Inc.", industry="SaaS / Data",
         biz_type="B2B", website="https://nimbusanalytics.io", email="hello@nimbusanalytics.io",
         phone="+1 415 555 0134", country="USA", currency="USD", founder="Humayra Shajahan",
         status="Active", started=date(2023, 1, 10), stage="Growth", theme="0D9488",
         notes="Core analytics platform, main focus company."),
    dict(name="Kiln & Co", legal="Kiln & Co Ltd.", industry="D2C / Home Goods",
         biz_type="B2C", website="https://kilnandco.com", email="team@kilnandco.com",
         phone="+44 20 7946 0958", country="UK", currency="GBP", founder="Humayra Shajahan",
         status="Active", started=date(2024, 1, 5), stage="Launched", theme="D97706",
         notes="Ceramics & homeware brand, seasonal demand."),
    dict(name="Pathlight Tutors", legal="Pathlight Education LLC", industry="EdTech",
         biz_type="B2C", website="https://pathlighttutors.com", email="support@pathlighttutors.com",
         phone="+1 646 555 0192", country="USA", currency="USD", founder="Humayra Shajahan",
         status="Exploring", started=date(2024, 8, 1), stage="Pre-Launch", theme="7C3AED",
         notes="Early-stage tutoring marketplace, validating demand."),
]

# ---- Projects -----------------------------------------------------------
# (company_id, name, description, priority, department, owner, status, start, end, est_hours)
PROJECTS = [
    ("COMP-0001", "Analytics Dashboard v2", "Rebuild core dashboard with faster queries.",
     "High", "Engineering", "Ali Raza", "In Progress", date(2026, 5, 1), date(2026, 9, 1), 320),
    ("COMP-0001", "Self-Serve Onboarding", "Reduce time-to-value for new signups.",
     "Critical", "Product", "Sara Khan", "In Progress", date(2026, 6, 15), date(2026, 8, 30), 180),
    ("COMP-0001", "SOC 2 Prep", "Get compliance docs and controls in place.",
     "Medium", "Operations", "Humayra Shajahan", "Not Started", date(2026, 9, 1), date(2026, 12, 15), 120),
    ("COMP-0002", "Winter Collection Launch", "Design, source, and launch winter line.",
     "High", "Marketing", "Bilal Ahmed", "In Progress", date(2026, 6, 1), date(2026, 10, 1), 260),
    ("COMP-0002", "Warehouse Automation", "Automate pick/pack workflow.",
     "Medium", "Operations", "Nadia Farooq", "In Progress", date(2026, 7, 1), date(2026, 11, 1), 150),
    ("COMP-0003", "MVP Marketplace Build", "Build tutor/student matching MVP.",
     "Critical", "Engineering", "Omar Siddiqui", "In Progress", date(2026, 6, 1), date(2026, 9, 15), 400),
    ("COMP-0003", "Market Validation Interviews", "Run 30 parent/tutor interviews.",
     "High", "Product", "Humayra Shajahan", "In Review", date(2026, 5, 1), date(2026, 7, 15), 40),
]

# ---- Tasks ----------------------------------------------------------------
# (project_index (1-based into PROJECTS), name, department, owner, task_type,
#  priority, status, created, due, completed, est_hours, notes)
TASKS = [
    (1, "Rewrite query layer for Postgres partitioning", "Engineering", "Ali Raza", "Feature", "High", "In Progress", date(2026, 6, 1), date(2026, 8, 1), None, 40, ""),
    (1, "Add caching layer for dashboard widgets", "Engineering", "Ali Raza", "Feature", "Medium", "Not Started", date(2026, 6, 5), date(2026, 8, 15), None, 24, ""),
    (1, "Fix chart rendering bug on Safari", "Engineering", "Ali Raza", "Bug", "High", "Completed", date(2026, 5, 10), date(2026, 5, 20), date(2026, 5, 18), 6, ""),
    (2, "Redesign signup flow wireframes", "Design", "Sara Khan", "Design", "Critical", "Completed", date(2026, 6, 16), date(2026, 6, 25), date(2026, 6, 24), 16, ""),
    (2, "Build interactive product tour", "Engineering", "Ali Raza", "Feature", "High", "In Progress", date(2026, 6, 26), date(2026, 8, 10), None, 32, ""),
    (2, "Write onboarding email sequence", "Marketing", "Bilal Ahmed", "Content", "Medium", "In Review", date(2026, 7, 1), date(2026, 7, 20), None, 10, ""),
    (3, "Draft security policy documents", "Operations", "Humayra Shajahan", "Admin", "Medium", "Not Started", date(2026, 9, 1), date(2026, 9, 30), None, 20, ""),
    (4, "Photograph winter collection lookbook", "Marketing", "Bilal Ahmed", "Content", "High", "In Progress", date(2026, 7, 1), date(2026, 7, 25), None, 18, ""),
    (4, "Negotiate supplier pricing for glaze materials", "Operations", "Nadia Farooq", "Ops", "High", "In Progress", date(2026, 6, 20), date(2026, 7, 30), None, 12, ""),
    (4, "Launch paid social campaign", "Marketing", "Bilal Ahmed", "Ops", "Critical", "Not Started", date(2026, 8, 15), date(2026, 9, 15), None, 20, ""),
    (5, "Map current pick/pack workflow", "Operations", "Nadia Farooq", "Research", "Medium", "Completed", date(2026, 7, 1), date(2026, 7, 10), date(2026, 7, 9), 14, ""),
    (5, "Evaluate 3 warehouse automation vendors", "Operations", "Nadia Farooq", "Research", "Medium", "In Progress", date(2026, 7, 11), date(2026, 8, 5), None, 18, ""),
    (6, "Build tutor profile + search UI", "Engineering", "Omar Siddiqui", "Feature", "Critical", "In Progress", date(2026, 6, 1), date(2026, 7, 20), None, 60, ""),
    (6, "Implement booking + payments flow", "Engineering", "Omar Siddiqui", "Feature", "Critical", "Not Started", date(2026, 7, 21), date(2026, 9, 1), None, 80, ""),
    (6, "Set up automated background checks", "Operations", "Omar Siddiqui", "Ops", "High", "Not Started", date(2026, 8, 1), date(2026, 9, 10), None, 16, ""),
    (7, "Interview 15 parents on tutoring pain points", "Product", "Humayra Shajahan", "Research", "High", "Completed", date(2026, 5, 1), date(2026, 6, 1), date(2026, 5, 30), 20, ""),
    (7, "Interview 15 tutors on marketplace expectations", "Product", "Humayra Shajahan", "Research", "High", "In Review", date(2026, 6, 2), date(2026, 7, 15), None, 20, ""),
]

# ---- Time Log --------------------------------------------------------------
# (task_index (1-based into TASKS), employee, log_date, start, end, break_mins, billable, category, notes)
TIME_LOG = [
    (1, "Ali Raza", date(2026, 7, 20), "09:00", "12:30", 15, "Yes", "Deep Work", "Query layer refactor"),
    (1, "Ali Raza", date(2026, 7, 21), "09:15", "13:00", 15, "Yes", "Deep Work", "Partition testing"),
    (2, "Ali Raza", date(2026, 7, 22), "10:00", "12:00", 0, "Yes", "Deep Work", "Cache design spike"),
    (3, "Ali Raza", date(2026, 5, 17), "14:00", "18:00", 15, "Yes", "Deep Work", "Safari bug repro + fix"),
    (4, "Sara Khan", date(2026, 6, 18), "09:00", "13:00", 15, "Yes", "Deep Work", "Wireframes v1"),
    (4, "Sara Khan", date(2026, 6, 20), "09:00", "12:00", 0, "Yes", "Deep Work", "Wireframes v2 + review"),
    (5, "Ali Raza", date(2026, 7, 24), "09:00", "12:00", 0, "Yes", "Deep Work", "Product tour scaffolding"),
    (6, "Bilal Ahmed", date(2026, 7, 10), "10:00", "12:30", 15, "Yes", "Shallow Work", "Email copy draft"),
    (8, "Bilal Ahmed", date(2026, 7, 15), "09:00", "14:00", 30, "Yes", "Shallow Work", "Product shoot day 1"),
    (8, "Bilal Ahmed", date(2026, 7, 16), "09:00", "13:00", 15, "Yes", "Shallow Work", "Product shoot day 2"),
    (9, "Nadia Farooq", date(2026, 7, 5), "13:00", "16:00", 0, "Yes", "Meeting", "Supplier call - glaze pricing"),
    (11, "Nadia Farooq", date(2026, 7, 3), "09:00", "12:00", 0, "Yes", "Deep Work", "Workflow mapping"),
    (12, "Nadia Farooq", date(2026, 7, 18), "10:00", "13:30", 15, "Yes", "Deep Work", "Vendor demo #1"),
    (13, "Omar Siddiqui", date(2026, 7, 8), "09:00", "13:00", 15, "Yes", "Deep Work", "Search UI build"),
    (13, "Omar Siddiqui", date(2026, 7, 9), "09:00", "13:30", 15, "Yes", "Deep Work", "Profile UI build"),
    (13, "Omar Siddiqui", date(2026, 7, 10), "09:00", "12:00", 0, "Yes", "Deep Work", "Search filters"),
    (16, "Humayra Shajahan", date(2026, 5, 20), "09:00", "11:00", 0, "No", "Meeting", "Parent interviews batch 1"),
    (17, "Humayra Shajahan", date(2026, 7, 5), "09:00", "11:30", 15, "No", "Meeting", "Tutor interviews batch 1"),
]
