"""Demo seed data for Phase 1 (Master Data, Companies, Projects, Tasks, Time Tracking).

Kept in one place so later phases (Finance, CRM, ...) can add rows that
reference these same IDs without hunting through sheet-builder code.
"""
from datetime import date

TODAY = date(2026, 7, 28)

# ---- Lookup lists -------------------------------------------------------
LOOKUPS = {
    "Departments": ["Engineering", "Product", "Design", "Marketing", "Sales",
                     "Finance", "Operations", "Customer Success", "Legal", "HR"],
    "Priority Levels": ["Critical", "High", "Medium", "Low"],
    "Statuses": ["Not Started", "In Progress", "Blocked", "In Review",
                 "Completed", "Cancelled", "On Hold"],
    "Company Status": ["Active", "Paused", "Archived", "Exploring"],
    "Company Stage": ["Idea", "Pre-Launch", "Launched", "Growth", "Scaling", "Mature"],
    "Task Types": ["Feature", "Bug", "Research", "Admin", "Meeting", "Content", "Design", "Ops"],
    "Currencies": ["USD", "GBP", "EUR", "PKR", "AED", "INR", "CAD", "AUD"],
    "Time Categories": ["Deep Work", "Shallow Work", "Meeting", "Admin", "Learning"],
    "Billable": ["Yes", "No"],
    "Employee Status": ["Active", "Inactive", "On Leave"],
    "Expense Categories": ["Software & Tools", "Payroll", "Contractors", "Marketing",
                            "Travel", "Office & Supplies", "Legal & Professional",
                            "Rent & Utilities", "Equipment", "Shipping & Fulfillment",
                            "Materials & Inventory", "Bank & Payment Fees", "Taxes", "Other"],
    "Revenue Categories": ["Product Sales", "Subscription Revenue", "Service Revenue",
                            "Consulting", "Licensing", "Interest Income", "Other Income"],
    "Payment Methods": ["Bank Transfer", "Credit Card", "Debit Card", "Cash",
                         "PayPal", "Stripe", "Check", "Wire Transfer"],
    "Approval Status": ["Pending", "Approved", "Rejected"],
    "Payment Status": ["Unpaid", "Paid", "Partially Paid", "Overdue"],
    "Invoice Status": ["Draft", "Sent", "Paid", "Overdue", "Cancelled"],
}

# ---- Employees ------------------------------------------------------------
# (Name, Email, Role, Department, Primary Company, Status, Start Date, Skills)
EMPLOYEES = [
    ("Humayra Shajahan", "humayrashajahan@gmail.com", "Founder / CEO", "Operations", "COMP-0001", "Active", date(2023, 1, 10), "Strategy, Fundraising, Product"),
    ("Ali Raza", "ali.raza@example.com", "Lead Engineer", "Engineering", "COMP-0001", "Active", date(2023, 3, 1), "Python, React, AWS"),
    ("Sara Khan", "sara.khan@example.com", "Product Designer", "Design", "COMP-0001", "Active", date(2023, 6, 15), "Figma, UX Research"),
    ("Bilal Ahmed", "bilal.ahmed@example.com", "Growth Marketer", "Marketing", "COMP-0002", "Active", date(2024, 1, 5), "SEO, Paid Ads, Content"),
    ("Nadia Farooq", "nadia.farooq@example.com", "Ops Manager", "Operations", "COMP-0002", "Active", date(2024, 2, 20), "Logistics, Vendor Mgmt"),
    ("Omar Siddiqui", "omar.siddiqui@example.com", "Full-Stack Engineer", "Engineering", "COMP-0003", "Active", date(2024, 8, 1), "Node.js, Postgres"),
]

# ---- Companies --------------------------------------------------------
# id will be auto-generated by formula; we just provide the seed fields in order
COMPANIES = [
    dict(name="Nimbus Analytics", legal="Nimbus Analytics Inc.", industry="SaaS / Data",
         biz_type="B2B", website="https://nimbusanalytics.io", email="hello@nimbusanalytics.io",
         phone="+1 415 555 0134", country="USA", currency="USD", founder="Humayra Shajahan",
         status="Active", started=date(2023, 1, 10), stage="Growth", theme="0D9488",
         notes="Core analytics platform, main focus company."),
    dict(name="Kiln & Co", legal="Kiln & Co Ltd.", industry="D2C / Home Goods",
         biz_type="B2C", website="https://kilnandco.com", email="team@kilnandco.com",
         phone="+44 20 7946 0958", country="UK", currency="GBP", founder="Humayra Shajahan",
         status="Active", started=date(2024, 1, 5), stage="Launched", theme="D97706",
         notes="Ceramics & homeware brand, seasonal demand."),
    dict(name="Pathlight Tutors", legal="Pathlight Education LLC", industry="EdTech",
         biz_type="B2C", website="https://pathlighttutors.com", email="support@pathlighttutors.com",
         phone="+1 646 555 0192", country="USA", currency="USD", founder="Humayra Shajahan",
         status="Exploring", started=date(2024, 8, 1), stage="Pre-Launch", theme="7C3AED",
         notes="Early-stage tutoring marketplace, validating demand."),
]

# ---- Projects -----------------------------------------------------------
# (company_id, name, description, priority, department, owner, status, start, end, est_hours)
PROJECTS = [
    ("COMP-0001", "Analytics Dashboard v2", "Rebuild core dashboard with faster queries.",
     "High", "Engineering", "Ali Raza", "In Progress", date(2026, 5, 1), date(2026, 9, 1), 320),
    ("COMP-0001", "Self-Serve Onboarding", "Reduce time-to-value for new signups.",
     "Critical", "Product", "Sara Khan", "In Progress", date(2026, 6, 15), date(2026, 8, 30), 180),
    ("COMP-0001", "SOC 2 Prep", "Get compliance docs and controls in place.",
     "Medium", "Operations", "Humayra Shajahan", "Not Started", date(2026, 9, 1), date(2026, 12, 15), 120),
    ("COMP-0002", "Winter Collection Launch", "Design, source, and launch winter line.",
     "High", "Marketing", "Bilal Ahmed", "In Progress", date(2026, 6, 1), date(2026, 10, 1), 260),
    ("COMP-0002", "Warehouse Automation", "Automate pick/pack workflow.",
     "Medium", "Operations", "Nadia Farooq", "In Progress", date(2026, 7, 1), date(2026, 11, 1), 150),
    ("COMP-0003", "MVP Marketplace Build", "Build tutor/student matching MVP.",
     "Critical", "Engineering", "Omar Siddiqui", "In Progress", date(2026, 6, 1), date(2026, 9, 15), 400),
    ("COMP-0003", "Market Validation Interviews", "Run 30 parent/tutor interviews.",
     "High", "Product", "Humayra Shajahan", "In Review", date(2026, 5, 1), date(2026, 7, 15), 40),
]

# ---- Tasks ----------------------------------------------------------------
# (project_index (1-based into PROJECTS), name, department, owner, task_type,
#  priority, status, created, due, completed, est_hours, notes)
TASKS = [
    (1, "Rewrite query layer for Postgres partitioning", "Engineering", "Ali Raza", "Feature", "High", "In Progress", date(2026, 6, 1), date(2026, 8, 1), None, 40, ""),
    (1, "Add caching layer for dashboard widgets", "Engineering", "Ali Raza", "Feature", "Medium", "Not Started", date(2026, 6, 5), date(2026, 8, 15), None, 24, ""),
    (1, "Fix chart rendering bug on Safari", "Engineering", "Ali Raza", "Bug", "High", "Completed", date(2026, 5, 10), date(2026, 5, 20), date(2026, 5, 18), 6, ""),
    (2, "Redesign signup flow wireframes", "Design", "Sara Khan", "Design", "Critical", "Completed", date(2026, 6, 16), date(2026, 6, 25), date(2026, 6, 24), 16, ""),
    (2, "Build interactive product tour", "Engineering", "Ali Raza", "Feature", "High", "In Progress", date(2026, 6, 26), date(2026, 8, 10), None, 32, ""),
    (2, "Write onboarding email sequence", "Marketing", "Bilal Ahmed", "Content", "Medium", "In Review", date(2026, 7, 1), date(2026, 7, 20), None, 10, ""),
    (3, "Draft security policy documents", "Operations", "Humayra Shajahan", "Admin", "Medium", "Not Started", date(2026, 9, 1), date(2026, 9, 30), None, 20, ""),
    (4, "Photograph winter collection lookbook", "Marketing", "Bilal Ahmed", "Content", "High", "In Progress", date(2026, 7, 1), date(2026, 7, 25), None, 18, ""),
    (4, "Negotiate supplier pricing for glaze materials", "Operations", "Nadia Farooq", "Ops", "High", "In Progress", date(2026, 6, 20), date(2026, 7, 30), None, 12, ""),
    (4, "Launch paid social campaign", "Marketing", "Bilal Ahmed", "Ops", "Critical", "Not Started", date(2026, 8, 15), date(2026, 9, 15), None, 20, ""),
    (5, "Map current pick/pack workflow", "Operations", "Nadia Farooq", "Research", "Medium", "Completed", date(2026, 7, 1), date(2026, 7, 10), date(2026, 7, 9), 14, ""),
    (5, "Evaluate 3 warehouse automation vendors", "Operations", "Nadia Farooq", "Research", "Medium", "In Progress", date(2026, 7, 11), date(2026, 8, 5), None, 18, ""),
    (6, "Build tutor profile + search UI", "Engineering", "Omar Siddiqui", "Feature", "Critical", "In Progress", date(2026, 6, 1), date(2026, 7, 20), None, 60, ""),
    (6, "Implement booking + payments flow", "Engineering", "Omar Siddiqui", "Feature", "Critical", "Not Started", date(2026, 7, 21), date(2026, 9, 1), None, 80, ""),
    (6, "Set up automated background checks", "Operations", "Omar Siddiqui", "Ops", "High", "Not Started", date(2026, 8, 1), date(2026, 9, 10), None, 16, ""),
    (7, "Interview 15 parents on tutoring pain points", "Product", "Humayra Shajahan", "Research", "High", "Completed", date(2026, 5, 1), date(2026, 6, 1), date(2026, 5, 30), 20, ""),
    (7, "Interview 15 tutors on marketplace expectations", "Product", "Humayra Shajahan", "Research", "High", "In Review", date(2026, 6, 2), date(2026, 7, 15), None, 20, ""),
]

# ---- Time Log --------------------------------------------------------------
# (task_index (1-based into TASKS), employee, log_date, start, end, break_mins, billable, category, notes)
TIME_LOG = [
    (1, "Ali Raza", date(2026, 7, 20), "09:00", "12:30", 15, "Yes", "Deep Work", "Query layer refactor"),
    (1, "Ali Raza", date(2026, 7, 21), "09:15", "13:00", 15, "Yes", "Deep Work", "Partition testing"),
    (2, "Ali Raza", date(2026, 7, 22), "10:00", "12:00", 0, "Yes", "Deep Work", "Cache design spike"),
    (3, "Ali Raza", date(2026, 5, 17), "14:00", "18:00", 15, "Yes", "Deep Work", "Safari bug repro + fix"),
    (4, "Sara Khan", date(2026, 6, 18), "09:00", "13:00", 15, "Yes", "Deep Work", "Wireframes v1"),
    (4, "Sara Khan", date(2026, 6, 20), "09:00", "12:00", 0, "Yes", "Deep Work", "Wireframes v2 + review"),
    (5, "Ali Raza", date(2026, 7, 24), "09:00", "12:00", 0, "Yes", "Deep Work", "Product tour scaffolding"),
    (6, "Bilal Ahmed", date(2026, 7, 10), "10:00", "12:30", 15, "Yes", "Shallow Work", "Email copy draft"),
    (8, "Bilal Ahmed", date(2026, 7, 15), "09:00", "14:00", 30, "Yes", "Shallow Work", "Product shoot day 1"),
    (8, "Bilal Ahmed", date(2026, 7, 16), "09:00", "13:00", 15, "Yes", "Shallow Work", "Product shoot day 2"),
    (9, "Nadia Farooq", date(2026, 7, 5), "13:00", "16:00", 0, "Yes", "Meeting", "Supplier call - glaze pricing"),
    (11, "Nadia Farooq", date(2026, 7, 3), "09:00", "12:00", 0, "Yes", "Deep Work", "Workflow mapping"),
    (12, "Nadia Farooq", date(2026, 7, 18), "10:00", "13:30", 15, "Yes", "Deep Work", "Vendor demo #1"),
    (13, "Omar Siddiqui", date(2026, 7, 8), "09:00", "13:00", 15, "Yes", "Deep Work", "Search UI build"),
    (13, "Omar Siddiqui", date(2026, 7, 9), "09:00", "13:30", 15, "Yes", "Deep Work", "Profile UI build"),
    (13, "Omar Siddiqui", date(2026, 7, 10), "09:00", "12:00", 0, "Yes", "Deep Work", "Search filters"),
    (16, "Humayra Shajahan", date(2026, 5, 20), "09:00", "11:00", 0, "No", "Meeting", "Parent interviews batch 1"),
    (17, "Humayra Shajahan", date(2026, 7, 5), "09:00", "11:30", 15, "No", "Meeting", "Tutor interviews batch 1"),
]

# ---- Vendors ----------------------------------------------------------------
# (Name, Category, Contact Name, Email, Phone, Payment Terms, Notes)
VENDORS = [
    ("AWS", "Software & Tools", "-", "billing@aws.amazon.com", "-", "Net 30", "Cloud hosting for Nimbus Analytics"),
    ("Figma", "Software & Tools", "-", "billing@figma.com", "-", "Net 15", "Design tooling"),
    ("Ceramics Supply Co", "Materials & Inventory", "Tom Reyes", "sales@ceramicsupply.com", "+44 161 555 0110", "Net 30", "Glaze & clay materials for Kiln & Co"),
    ("Meta Ads", "Marketing", "-", "support@meta.com", "-", "Due on receipt", "Paid social campaigns"),
    ("WeWork", "Rent & Utilities", "-", "billing@wework.com", "-", "Net 15", "Shared office space"),
    ("Upwork Contractor - J. Lee", "Contractors", "Jamie Lee", "jamie.lee@example.com", "-", "Net 15", "Freelance dev support"),
]

# ---- Expenses -----------------------------------------------------------------
# (company_id, project_index or None, category, vendor, date, amount, currency, tax,
#  payment_method, paid_by, reimbursable, reimbursed, reimb_date, approval, payment_status,
#  receipt_link, notes)
EXPENSES = [
    ("COMP-0001", 1, "Software & Tools", "AWS", date(2026, 7, 1), 640.00, "USD", 0.00,
     "Credit Card", "Nimbus Analytics", "No", "No", None, "Approved", "Paid",
     "https://drive.google.com/file/d/aws-jul-invoice", "Monthly cloud hosting"),
    ("COMP-0001", None, "Software & Tools", "Figma", date(2026, 7, 3), 45.00, "USD", 0.00,
     "Credit Card", "Nimbus Analytics", "No", "No", None, "Approved", "Paid",
     "https://drive.google.com/file/d/figma-jul-invoice", "Design seats"),
    ("COMP-0001", 2, "Contractors", "Upwork Contractor - J. Lee", date(2026, 7, 12), 1200.00, "USD", 0.00,
     "Bank Transfer", "Nimbus Analytics", "No", "No", None, "Approved", "Paid",
     "", "Onboarding flow contractor sprint"),
    ("COMP-0001", None, "Rent & Utilities", "WeWork", date(2026, 7, 1), 450.00, "USD", 0.00,
     "Bank Transfer", "Nimbus Analytics", "No", "No", None, "Approved", "Paid",
     "", "Monthly desk membership"),
    ("COMP-0001", 3, "Legal & Professional", "-", date(2026, 6, 20), 850.00, "USD", 0.00,
     "Bank Transfer", "Humayra Shajahan", "Yes", "No", None, "Approved", "Unpaid",
     "", "SOC 2 readiness consultation"),
    ("COMP-0001", None, "Travel", "-", date(2026, 6, 5), 312.40, "USD", 0.00,
     "Credit Card", "Humayra Shajahan", "Yes", "Yes", date(2026, 6, 20), "Approved", "Paid",
     "https://drive.google.com/file/d/travel-receipt-1", "Investor meeting flight"),
    ("COMP-0002", 4, "Materials & Inventory", "Ceramics Supply Co", date(2026, 7, 2), 2140.00, "GBP", 0.00,
     "Wire Transfer", "Kiln & Co", "No", "No", None, "Approved", "Paid",
     "https://drive.google.com/file/d/ceramics-jul", "Glaze restock for winter line"),
    ("COMP-0002", 4, "Marketing", "Meta Ads", date(2026, 7, 8), 600.00, "GBP", 0.00,
     "Credit Card", "Kiln & Co", "No", "No", None, "Approved", "Paid",
     "", "Lookbook boost campaign"),
    ("COMP-0002", None, "Shipping & Fulfillment", "-", date(2026, 7, 10), 380.75, "GBP", 0.00,
     "Debit Card", "Nadia Farooq", "Yes", "No", None, "Pending", "Unpaid",
     "https://drive.google.com/file/d/shipping-receipt-1", "Courier costs for wholesale batch"),
    ("COMP-0002", 5, "Equipment", "-", date(2026, 6, 28), 1450.00, "GBP", 0.00,
     "Bank Transfer", "Kiln & Co", "No", "No", None, "Approved", "Paid",
     "", "Conveyor sensor for pick/pack pilot"),
    ("COMP-0002", None, "Office & Supplies", "-", date(2026, 7, 14), 96.20, "GBP", 0.00,
     "Debit Card", "Nadia Farooq", "Yes", "Yes", date(2026, 7, 22), "Approved", "Paid",
     "", "Packaging samples"),
    ("COMP-0003", 6, "Contractors", "Upwork Contractor - J. Lee", date(2026, 7, 5), 900.00, "USD", 0.00,
     "Bank Transfer", "Pathlight Tutors", "No", "No", None, "Approved", "Paid",
     "", "Background-check API integration"),
    ("COMP-0003", None, "Legal & Professional", "-", date(2026, 6, 10), 500.00, "USD", 0.00,
     "Bank Transfer", "Humayra Shajahan", "Yes", "No", None, "Pending", "Unpaid",
     "", "Marketplace terms of service draft"),
    ("COMP-0003", None, "Software & Tools", "-", date(2026, 7, 1), 29.00, "USD", 0.00,
     "Credit Card", "Pathlight Tutors", "No", "No", None, "Approved", "Paid",
     "", "Survey tooling for parent interviews"),
]

# ---- Revenue --------------------------------------------------------------
# (company_id, project_index or None, client, category, date, amount, currency,
#  payment_status, invoice_index or None, notes)
REVENUE = [
    ("COMP-0001", None, "Beacon Retail Group", "Subscription Revenue", date(2026, 5, 1), 4200.00, "USD", "Paid", 1, "May subscription"),
    ("COMP-0001", None, "Beacon Retail Group", "Subscription Revenue", date(2026, 6, 1), 4200.00, "USD", "Paid", 2, "June subscription"),
    ("COMP-0001", None, "Beacon Retail Group", "Subscription Revenue", date(2026, 7, 1), 4600.00, "USD", "Paid", 3, "July subscription, seat upgrade"),
    ("COMP-0001", None, "Harlow & Finch", "Subscription Revenue", date(2026, 6, 1), 1800.00, "USD", "Paid", 4, "June subscription"),
    ("COMP-0001", None, "Harlow & Finch", "Subscription Revenue", date(2026, 7, 1), 1800.00, "USD", "Paid", 5, "July subscription"),
    ("COMP-0001", 1, "Vantage Point Capital", "Consulting", date(2026, 7, 15), 3000.00, "USD", "Unpaid", 6, "Custom dashboard consulting engagement"),
    ("COMP-0002", None, "Direct-to-Consumer Store", "Product Sales", date(2026, 6, 5), 3120.50, "GBP", "Paid", None, "Online store, May batch"),
    ("COMP-0002", None, "Direct-to-Consumer Store", "Product Sales", date(2026, 7, 5), 4580.25, "GBP", "Paid", None, "Online store, June batch"),
    ("COMP-0002", None, "The Nook Homeware", "Product Sales", date(2026, 6, 18), 1250.00, "GBP", "Paid", 7, "Wholesale order #1"),
    ("COMP-0002", None, "The Nook Homeware", "Product Sales", date(2026, 7, 20), 1875.00, "GBP", "Unpaid", 8, "Wholesale order #2"),
    ("COMP-0003", 7, "Riverside Family Co-op", "Service Revenue", date(2026, 7, 10), 450.00, "USD", "Paid", None, "Pilot tutoring sessions"),
]

# ---- Invoices -----------------------------------------------------------------
# (company_id, client, currency, amount, issue_date, due_date, status, paid_date, notes)
INVOICES = [
    ("COMP-0001", "Beacon Retail Group", "USD", 4200.00, date(2026, 5, 1), date(2026, 5, 15), "Paid", date(2026, 5, 10), "May subscription invoice"),
    ("COMP-0001", "Beacon Retail Group", "USD", 4200.00, date(2026, 6, 1), date(2026, 6, 15), "Paid", date(2026, 6, 12), "June subscription invoice"),
    ("COMP-0001", "Beacon Retail Group", "USD", 4600.00, date(2026, 7, 1), date(2026, 7, 15), "Paid", date(2026, 7, 9), "July subscription invoice"),
    ("COMP-0001", "Harlow & Finch", "USD", 1800.00, date(2026, 6, 1), date(2026, 6, 15), "Paid", date(2026, 6, 14), "June subscription invoice"),
    ("COMP-0001", "Harlow & Finch", "USD", 1800.00, date(2026, 7, 1), date(2026, 7, 15), "Paid", date(2026, 7, 11), "July subscription invoice"),
    ("COMP-0001", "Vantage Point Capital", "USD", 3000.00, date(2026, 7, 15), date(2026, 8, 14), "Sent", None, "Consulting engagement, net 30"),
    ("COMP-0002", "The Nook Homeware", "GBP", 1250.00, date(2026, 6, 18), date(2026, 7, 2), "Paid", date(2026, 6, 30), "Wholesale order #1"),
    ("COMP-0002", "The Nook Homeware", "GBP", 1875.00, date(2026, 7, 20), date(2026, 8, 3), "Sent", None, "Wholesale order #2"),
]

# ---- Budgets --------------------------------------------------------------------
# (company_id, category, month, budgeted_amount)
BUDGETS = [
    ("COMP-0001", "Software & Tools", date(2026, 7, 1), 800.00),
    ("COMP-0001", "Contractors", date(2026, 7, 1), 1500.00),
    ("COMP-0001", "Rent & Utilities", date(2026, 7, 1), 500.00),
    ("COMP-0002", "Materials & Inventory", date(2026, 7, 1), 2500.00),
    ("COMP-0002", "Marketing", date(2026, 7, 1), 800.00),
    ("COMP-0002", "Shipping & Fulfillment", date(2026, 7, 1), 500.00),
    ("COMP-0003", "Contractors", date(2026, 7, 1), 1000.00),
    ("COMP-0003", "Legal & Professional", date(2026, 7, 1), 600.00),
    ("COMP-0003", "Software & Tools", date(2026, 7, 1), 100.00),
]
